### ISSUE TITLE
Feature extraction problem

### ISSUE THREAD

**Issue by nd39** [r9y9/nnmnkwii_gallery#1]
Hi,
I was trying your code on my own database, however an error came out in the stage of feature extraction when using the commande line ! python ./scripts/prepare_features.py ./data/slt_arctic_full_data
which is : 

Traceback (most recent call last):
  File "./scripts/prepare_features.py", line 226, in <module>
    print("Acoustic linguistic feature dim", X_acoustic[0].shape)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nnmnkwii/datasets/__init__.py", line 146, in __getitem__
    return self.__collect_features(paths)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nnmnkwii/datasets/__init__.py", line 131, in __collect_features
    return self.file_data_source.collect_features(*paths)
  File "./scripts/prepare_features.py", line 75, in collect_features
    subphone_features=self.subphone_features)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nnmnkwii/frontend/merlin.py", line 511, in linguistic_features
    return load_labels_with_phone_alignment(hts_labels, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nnmnkwii/frontend/merlin.py", line 238, in load_labels_with_phone_alignment
    subphone_features, add_frame_features))
ValueError: Combination of subphone_features and add_frame_features is not supported: full, True

Coud you help me solve it.
Thank you in advance.

**Comment by r9y9** [comment]
Which notebook did you run?

**Comment by nd39** [comment]
the notebook of Bidirectional-LSTM based RNNs for text-to-speech synthesis

**Comment by r9y9** [comment]
Sorry for the delay. I tried but cannot reproduce. What changes did you make? What does your data look like?

**Comment by nd39** [comment]
thank you, I solve it, the problem was my label state alignment. I have another question, if i want to use the label phone alignment insteed of label state alignment, what changes should i make.

**Comment by r9y9** [comment]
http://nbviewer.jupyter.org/github/r9y9/nnmnkwii_gallery/blob/master/notebooks/tts/jp-01-DNN-based%20statistical%20speech%20synthesis.ipynb uses phone-level alignment for Japanese TTS and it might help to see what changes you need.

**Comment by nd39** [comment]
Thank you  for  helping me.

**Comment by mrgloom** [comment]
Get same error using `./nnmnkwii_gallery/data/slt_arctic_full_data/label_phone_align/arctic_b0538.lab` but for `./nnmnkwii_gallery/data/slt_arctic_full_data/label_state_align/arctic_b0538.lab` it's ok.
